20.times do
  Task.create title: Faker::Lorem.sentence, desc: Faker::Lorem.paragraph
end

Eteam.create(eteam_id: 'POL', team_name: 'Poland', coach: 'Franciszek Smuda')
Eteam.create(eteam_id: 'RUS', team_name: 'Russia', coach: 'Dick Advocaat')
Eteam.create(eteam_id: 'CZE', team_name: 'Czech Republic', coach: 'Michal Bílek')
Eteam.create(eteam_id: 'GRE', team_name: 'Greece', coach: 'Fernando Santos')
Eteam.create(eteam_id: 'NED', team_name: 'Netherlands', coach: 'Bert van Marwijk')
Eteam.create(eteam_id: 'DEN', team_name: 'Denmark', coach: 'Morten Olsen')
Eteam.create(eteam_id: 'GER', team_name: 'Germany', coach: 'Joachim Löw')
Eteam.create(eteam_id: 'POR', team_name: 'Portugal', coach: 'Paulo Bento')
Eteam.create(eteam_id: 'ESP', team_name: 'Spain', coach: 'Vicente del Bosque')
Eteam.create(eteam_id: 'ITA', team_name: 'Italy', coach: 'Cesare Prandelli')
Eteam.create(eteam_id: 'IRL', team_name: 'Republic of Ireland', coach: 'Giovanni Trapattoni')
Eteam.create(eteam_id: 'CRO', team_name: 'Croatia', coach: 'Slaven Bilic')
Eteam.create(eteam_id: 'UKR', team_name: 'Ukraine', coach: 'Oleh Blokhin')
Eteam.create(eteam_id: 'SWE', team_name: 'Sweden', coach: 'Erik Hamrén')
Eteam.create(eteam_id: 'ENG', team_name: 'England', coach: 'Roy Hodgson')
Eteam.create(eteam_id: 'FRA', team_name: 'France', coach: 'Laurent Blanc')

Game.create(game_id: '1001', mdate: '8 June 2012', stadium: 'National Stadium, Warsaw', team1: 'POL', team2: 'GRE')
Game.create(game_id: '1002', mdate: '8 June 2012', stadium: 'Stadion Miejski (Wroclaw)', team1: 'RUS', team2: 'CZE')
Game.create(game_id: '1003', mdate: '12 June 2012', stadium: 'Stadion Miejski (Wroclaw)', team1: 'GRE', team2: 'CZE')
Game.create(game_id: '1004', mdate: '12 June 2012', stadium: 'National Stadium, Warsaw', team1: 'POL', team2: 'RUS')
Game.create(game_id: '1005', mdate: '16 June 2012', stadium: 'Stadion Miejski (Wroclaw)', team1: 'CZE', team2: 'POL')
Game.create(game_id: '1006', mdate: '16 June 2012', stadium: 'National Stadium, Warsaw', team1: 'GRE', team2: 'RUS')
Game.create(game_id: '1007', mdate: '9 June 2012', stadium: 'Metalist Stadium', team1: 'NED', team2: 'DEN')
Game.create(game_id: '1008', mdate: '9 June 2012', stadium: 'Arena Lviv', team1: 'GER', team2: 'POR')
Game.create(game_id: '1009', mdate: '13 June 2012', stadium: 'Arena Lviv', team1: 'DEN', team2: 'POR')
Game.create(game_id: '1010', mdate: '13 June 2012', stadium: 'Metalist Stadium', team1: 'NED', team2: 'GER')
Game.create(game_id: '1011', mdate: '17 June 2012', stadium: 'Metalist Stadium', team1: 'POR', team2: 'NED')
Game.create(game_id: '1012', mdate: '17 June 2012', stadium: 'Arena Lviv', team1: 'DEN', team2: 'GER')
Game.create(game_id: '1013', mdate: '10 June 2012', stadium: 'PGE Arena Gdansk', team1: 'ESP', team2: 'ITA')
Game.create(game_id: '1014', mdate: '10 June 2012', stadium: 'Stadion Miejski (Poznan)', team1: 'IRL', team2: 'CRO')
Game.create(game_id: '1015', mdate: '14 June 2012', stadium: 'Stadion Miejski (Poznan)', team1: 'ITA', team2: 'CRO')
Game.create(game_id: '1016', mdate: '14 June 2012', stadium: 'PGE Arena Gdansk', team1: 'ESP', team2: 'IRL')
Game.create(game_id: '1017', mdate: '18 June 2012', stadium: 'PGE Arena Gdansk', team1: 'CRO', team2: 'ESP')
Game.create(game_id: '1018', mdate: '18 June 2012', stadium: 'Stadion Miejski (Poznan)', team1: 'ITA', team2: 'IRL')
Game.create(game_id: '1019', mdate: '11 June 2012', stadium: 'Donbass Arena', team1: 'FRA', team2: 'ENG')
Game.create(game_id: '1020', mdate: '11 June 2012', stadium: 'Olimpiyskiy National Sports Complex', team1: 'UKR', team2: 'SWE')
Game.create(game_id: '1021', mdate: '15 June 2012', stadium: 'Donbass Arena', team1: 'UKR', team2: 'FRA')
Game.create(game_id: '1022', mdate: '15 June 2012', stadium: 'Olimpiyskiy National Sports Complex', team1: 'SWE', team2: 'ENG')
Game.create(game_id: '1023', mdate: '19 June 2012', stadium: 'Donbass Arena', team1: 'ENG', team2: 'UKR')
Game.create(game_id: '1024', mdate: '19 June 2012', stadium: 'Olimpiyskiy National Sports Complex', team1: 'SWE', team2: 'FRA')
Game.create(game_id: '1025', mdate: '21 June 2012', stadium: 'National Stadium, Warsaw', team1: 'CZE', team2: 'POR')
Game.create(game_id: '1026', mdate: '22 June 2012', stadium: 'PGE Arena Gdansk', team1: 'GER', team2: 'GRE')
Game.create(game_id: '1027', mdate: '23 June 2012', stadium: 'Donbass Arena', team1: 'ESP', team2: 'FRA')
Game.create(game_id: '1028', mdate: '24 June 2012', stadium: 'Olimpiyskiy National Sports Complex', team1: 'ENG', team2: 'ITA')
Game.create(game_id: '1029', mdate: '27 June 2012', stadium: 'Donbass Arena', team1: 'POR', team2: 'ESP')
Game.create(game_id: '1030', mdate: '28 June 2012', stadium: 'National Stadium, Warsaw', team1: 'GER', team2: 'ITA')
Game.create(game_id: '1031', mdate: '1 July 2012', stadium: 'Olimpiyskiy National Sports Complex', team1: 'ESP', team2: 'ITA')

Goal.create(match_id: '1001', team_id: 'POL', player: 'Robert Lewandowski', gtime: '17')
Goal.create(match_id: '1001', team_id: 'GRE', player: 'Dimitris Salpingidis', gtime: '51')
Goal.create(match_id: '1002', team_id: 'RUS', player: 'Alan Dzagoev', gtime: '15')
Goal.create(match_id: '1002', team_id: 'RUS', player: 'Roman Shirokov', gtime: '24')
Goal.create(match_id: '1002', team_id: 'CZE', player: 'Václav Pilar', gtime: '52')
Goal.create(match_id: '1002', team_id: 'RUS', player: 'Alan Dzagoev', gtime: '79')
Goal.create(match_id: '1002', team_id: 'RUS', player: 'Roman Pavlyuchenko', gtime: '82')
Goal.create(match_id: '1003', team_id: 'CZE', player: 'Petr Jirácek', gtime: '3')
Goal.create(match_id: '1003', team_id: 'CZE', player: 'Václav Pilar', gtime: '6')
Goal.create(match_id: '1003', team_id: 'GRE', player: 'Theofanis Gekas', gtime: '53')
Goal.create(match_id: '1004', team_id: 'RUS', player: 'Alan Dzagoev', gtime: '37')
Goal.create(match_id: '1004', team_id: 'POL', player: 'Jakub Blaszczykowski', gtime: '57')
Goal.create(match_id: '1005', team_id: 'CZE', player: 'Petr Jirácek', gtime: '72')
Goal.create(match_id: '1006', team_id: 'GRE', player: 'Giorgos Karagounis', gtime: '45')
Goal.create(match_id: '1007', team_id: 'DEN', player: 'Michael Krohn-Dehli', gtime: '24')
Goal.create(match_id: '1008', team_id: 'GER', player: 'Mario Gómez', gtime: '72')
Goal.create(match_id: '1009', team_id: 'POR', player: 'Pepe (footballer born 1983)', gtime: '24')
Goal.create(match_id: '1009', team_id: 'POR', player: 'Hélder Postiga', gtime: '36')
Goal.create(match_id: '1009', team_id: 'DEN', player: 'Nicklas Bendtner', gtime: '41')
Goal.create(match_id: '1009', team_id: 'DEN', player: 'Nicklas Bendtner', gtime: '80')
Goal.create(match_id: '1009', team_id: 'POR', player: 'Silvestre Varela', gtime: '87')
Goal.create(match_id: '1010', team_id: 'GER', player: 'Mario Gómez', gtime: '24')
Goal.create(match_id: '1010', team_id: 'GER', player: 'Mario Gómez', gtime: '38')
Goal.create(match_id: '1010', team_id: 'NED', player: 'Robin van Persie', gtime: '73')
Goal.create(match_id: '1011', team_id: 'NED', player: 'Rafael van der Vaart', gtime: '11')
Goal.create(match_id: '1011', team_id: 'POR', player: 'Cristiano Ronaldo', gtime: '28')
Goal.create(match_id: '1011', team_id: 'POR', player: 'Cristiano Ronaldo', gtime: '74')
Goal.create(match_id: '1012', team_id: 'GER', player: 'Lukas Podolski', gtime: '19')
Goal.create(match_id: '1012', team_id: 'DEN', player: 'Michael Krohn-Dehli', gtime: '24')
Goal.create(match_id: '1012', team_id: 'GER', player: 'Lars Bender', gtime: '80')
Goal.create(match_id: '1013', team_id: 'ITA', player: 'Antonio Di Natale', gtime: '61')
Goal.create(match_id: '1013', team_id: 'ESP', player: 'Cesc Fàbregas', gtime: '64')
Goal.create(match_id: '1014', team_id: 'CRO', player: 'Mario Mandžukic', gtime: '3')
Goal.create(match_id: '1014', team_id: 'IRL', player: 'Sean St Ledger', gtime: '19')
Goal.create(match_id: '1014', team_id: 'CRO', player: 'Nikica Jelavic', gtime: '43')
Goal.create(match_id: '1014', team_id: 'CRO', player: 'Mario Mandžukic', gtime: '49')
Goal.create(match_id: '1015', team_id: 'ITA', player: 'Andrea Pirlo', gtime: '39')
Goal.create(match_id: '1015', team_id: 'CRO', player: 'Mario Mandžukic', gtime: '72')
Goal.create(match_id: '1016', team_id: 'ESP', player: 'Fernando Torres', gtime: '4')
Goal.create(match_id: '1016', team_id: 'ESP', player: 'David Silva', gtime: '49')
Goal.create(match_id: '1016', team_id: 'ESP', player: 'Fernando Torres', gtime: '70')
Goal.create(match_id: '1016', team_id: 'ESP', player: 'Cesc Fàbregas', gtime: '83')
Goal.create(match_id: '1017', team_id: 'ESP', player: 'Jesús Navas', gtime: '88')
Goal.create(match_id: '1018', team_id: 'ITA', player: 'Antonio Cassano', gtime: '35')
Goal.create(match_id: '1018', team_id: 'ITA', player: 'Mario Balotelli', gtime: '90')
Goal.create(match_id: '1019', team_id: 'ENG', player: 'Joleon Lescott', gtime: '30')
Goal.create(match_id: '1019', team_id: 'FRA', player: 'Samir Nasri', gtime: '39')
Goal.create(match_id: '1020', team_id: 'SWE', player: 'Zlatan Ibrahimovic', gtime: '52')
Goal.create(match_id: '1020', team_id: 'UKR', player: 'Andriy Shevchenko', gtime: '55')
Goal.create(match_id: '1020', team_id: 'UKR', player: 'Andriy Shevchenko', gtime: '62')
Goal.create(match_id: '1021', team_id: 'FRA', player: 'Jérémy Ménez', gtime: '53')
Goal.create(match_id: '1021', team_id: 'FRA', player: 'Yohan Cabaye', gtime: '56')
Goal.create(match_id: '1022', team_id: 'ENG', player: 'Andy Carroll', gtime: '23')
Goal.create(match_id: '1022', team_id: 'SWE', player: 'Glen Johnson (English footballer)', gtime: '49')
Goal.create(match_id: '1022', team_id: 'SWE', player: 'Olof Mellberg', gtime: '59')
Goal.create(match_id: '1022', team_id: 'ENG', player: 'Theo Walcott', gtime: '64')
Goal.create(match_id: '1022', team_id: 'ENG', player: 'Danny Welbeck', gtime: '78')
Goal.create(match_id: '1023', team_id: 'ENG', player: 'Wayne Rooney', gtime: '48')
Goal.create(match_id: '1024', team_id: 'SWE', player: 'Zlatan Ibrahimovic', gtime: '54')
Goal.create(match_id: '1024', team_id: 'SWE', player: 'Sebastian Larsson', gtime: '90')
Goal.create(match_id: '1025', team_id: 'POR', player: 'Cristiano Ronaldo', gtime: '79')
Goal.create(match_id: '1026', team_id: 'GER', player: 'Philipp Lahm', gtime: '39')
Goal.create(match_id: '1026', team_id: 'GRE', player: 'Georgios Samaras', gtime: '55')
Goal.create(match_id: '1026', team_id: 'GER', player: 'Sami Khedira', gtime: '61')
Goal.create(match_id: '1026', team_id: 'GER', player: 'Miroslav Klose', gtime: '68')
Goal.create(match_id: '1026', team_id: 'GER', player: 'Marco Reus', gtime: '74')
Goal.create(match_id: '1026', team_id: 'GRE', player: 'Dimitris Salpingidis', gtime: '89')
Goal.create(match_id: '1027', team_id: 'ESP', player: 'Xabi Alonso', gtime: '19')
Goal.create(match_id: '1027', team_id: 'ESP', player: 'Xabi Alonso', gtime: '90')
Goal.create(match_id: '1030', team_id: 'ITA', player: 'Mario Balotelli', gtime: '20')
Goal.create(match_id: '1030', team_id: 'ITA', player: 'Mario Balotelli', gtime: '36')
Goal.create(match_id: '1030', team_id: 'GER', player: 'Mesut Özil', gtime: '90')
Goal.create(match_id: '1031', team_id: 'ESP', player: 'David Silva', gtime: '14')
Goal.create(match_id: '1031', team_id: 'ESP', player: 'Jordi Alba', gtime: '41')
Goal.create(match_id: '1031', team_id: 'ESP', player: 'Fernando Torres', gtime: '84')
Goal.create(match_id: '1031', team_id: 'ESP', player: 'Juan Mata', gtime: '88')
